### ISSUE TITLE
error management upload page 

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/b-b#11]
in Firefox and in chrome after darg&dropin the file, if the file has errors, the blue button will not appear but the errors aren't displayed

**Comment by lucasverra** [comment]
plus error display is not accord to specification, please re-read error management texts on spec

**Comment by tmsmldr** [comment]
Hi @gsanikidze 

I made some tests yesterday and it seems to me that this issue is not solved yet.  Can you check please ? 
Maybe it is just that yesterday changes are not pushed yet. 
i have tested in chrome & firefox. 

Also at some point there was a like a green loading progress bar that was displayed near the file name. Of cours is was not specified so is not mandatory but it was really useful to know when the file is completly uploaded. If you can put the progress bar back it would be nice.

**Comment by lucasverra** [comment]
also tested in ff and @tmsmldr is correct

**Comment by lucasverra** [comment]
as chatted with tomas , this issue is to be closed

**Comment by tmsmldr** [comment]
Hello. 

The issue can not be closed yet. The errors must show the text specified in the spec. (now displaying english errors)

Also the rule 1 to check is not working completely as defined. The error message corresponding to the check rule 1 is shown when there are value missing on the column (that's is ok) but when the columns is not present in the file. The app does not display "the error rule number 1".

**Comment by tmsmldr** [comment]
Hello this is a loom message explanning the last little problem with this issue : 
https://www.loom.com/share/d136f26ac43c4ab6bf48408391d83ded
